#!/bin/sh
# Offline test harness for install.sh.
#
# Runs install.sh for real behind two PATH stubs, so no network access is
# needed: a stub curl that serves generated fixture files (and logs every
# requested URL), and a stub uname that reports the platform under test.
# Every case runs in a fresh temporary work directory with its own stubs,
# fixtures, install dir, XDG data dir, and HOME, so nothing here touches
# the real environment.
#
# Usage: scripts/test-install.sh (works from any cwd; the repo root is
# resolved relative to this file).

set -eu

SCRIPT_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH='' cd -- "$SCRIPT_DIR/.." && pwd)
INSTALL_SH=$REPO_ROOT/install.sh

WORK_ROOT=$(mktemp -d)
trap 'rm -rf "$WORK_ROOT"' EXIT INT TERM HUP

pass=0
fail=0
case_num=0
cur_case=
case_failed=0
case_work=
case_out=
case_status=
uname_s=Linux
uname_m=x86_64
unset_xdg=0

record_fail() {
    if [ "$case_failed" -eq 0 ]; then
        printf 'FAIL %d %s\n' "$case_num" "$cur_case"
        case_failed=1
        if [ -f "$case_out" ]; then
            printf '  output:\n'
            sed 's/^/  | /' "$case_out"
        fi
    fi
    printf '  %s\n' "$1"
}

begin_case() {
    case_num=$((case_num + 1))
    cur_case=$1
    case_failed=0
    case_work=$(mktemp -d "$WORK_ROOT/case.XXXXXX")
    mkdir -p "$case_work/bin" "$case_work/fixtures" "$case_work/install" \
        "$case_work/data" "$case_work/home"
    make_fixtures "$case_work"
    write_stubs "$case_work"
    uname_s=Linux
    uname_m=x86_64
    unset_xdg=0
    case_out=$case_work/out.log
    case_status=
}

end_case() {
    if [ "$case_failed" -eq 0 ]; then
        pass=$((pass + 1))
        printf 'ok %d %s\n' "$case_num" "$cur_case"
    else
        fail=$((fail + 1))
    fi
}

make_fixtures() {
    fx=$1/fixtures
    printf '#!/bin/sh\necho patok-fixture-binary\n' >"$fx/patok"
    chmod 755 "$fx/patok"
    for t in x86_64-unknown-linux-musl aarch64-apple-darwin x86_64-apple-darwin; do
        tar -czf "$fx/patok-$t.tar.gz" -C "$fx" patok
    done
    : >"$fx/checksums"
    for t in x86_64-unknown-linux-musl aarch64-apple-darwin x86_64-apple-darwin; do
        hash=$(sha256sum "$fx/patok-$t.tar.gz" | cut -d ' ' -f 1)
        printf '%s  patok-%s.tar.gz\n' "$hash" "$t" >>"$fx/checksums"
    done
    printf '{"tag_name": "v1.2.3"}\n' >"$fx/release.json"
}

write_stubs() {
    bin=$1/bin
    cat >"$bin/curl" <<'EOF'
#!/bin/sh
# Stub curl generated by scripts/test-install.sh (never checked in).
# Serves fixture files by URL suffix, logs every requested URL to
# urls.log next to the fixtures, and exits 22 for any URL listed in
# the curl-fail file.
set -u

fx=${STUB_FIXTURES:?STUB_FIXTURES not set}

url=
out=
prev=
for arg in "$@"; do
    if [ "$prev" = "-o" ]; then
        out=$arg
        prev=
    elif [ "$prev" = "-H" ]; then
        prev=
    else
        case $arg in
            -o | -H) prev=$arg ;;
            -*) ;;
            *) url=$arg ;;
        esac
    fi
done

if [ -z "$url" ]; then
    echo "stub curl: no URL requested" >&2
    exit 1
fi
if [ -z "$out" ]; then
    echo "stub curl: no -o output path given" >&2
    exit 1
fi

printf '%s\n' "$url" >>"$fx/urls.log"

if [ -f "$fx/curl-fail" ] && grep -qF -- "$url" "$fx/curl-fail"; then
    echo "stub curl: simulated failure for $url" >&2
    exit 22
fi

case $url in
    */releases/latest) cat "$fx/release.json" >"$out" ;;
    */checksums) cat "$fx/checksums" >"$out" ;;
    *)
        base=${url##*/}
        if [ -f "$fx/$base" ]; then
            cat "$fx/$base" >"$out"
        else
            echo "stub curl: no fixture for $url" >&2
            exit 1
        fi
        ;;
esac
EOF
    chmod 755 "$bin/curl"
    cat >"$bin/uname" <<'EOF'
#!/bin/sh
# Stub uname generated by scripts/test-install.sh (never checked in).
case ${1:-} in
    -s) printf '%s\n' "${STUB_UNAME_S:?STUB_UNAME_S not set}" ;;
    -m) printf '%s\n' "${STUB_UNAME_M:?STUB_UNAME_M not set}" ;;
    *) echo "stub uname: unexpected arguments: $*" >&2; exit 1 ;;
esac
EOF
    chmod 755 "$bin/uname"
}

run_install() {
    case_status=0
    (
        PATH="$case_work/bin:$PATH"
        PATOK_REPO=test/test
        PATOK_INSTALL_DIR="$case_work/install"
        HOME="$case_work/home"
        STUB_FIXTURES="$case_work/fixtures"
        STUB_UNAME_S="$uname_s"
        STUB_UNAME_M="$uname_m"
        export PATH PATOK_REPO PATOK_INSTALL_DIR HOME STUB_FIXTURES
        export STUB_UNAME_S STUB_UNAME_M
        if [ "$unset_xdg" -eq 1 ]; then
            unset XDG_DATA_HOME
        else
            XDG_DATA_HOME="$case_work/data"
            export XDG_DATA_HOME
        fi
        exec sh "$INSTALL_SH" "$@"
    ) >"$case_out" 2>&1 || case_status=$?
}

assert_status() {
    if [ "$case_status" != "$1" ]; then
        record_fail "expected exit status $1, got $case_status"
    fi
}

assert_contains() {
    grep -qF -- "$1" "$case_out" ||
        record_fail "expected output to contain: $1"
}

assert_file_equals() {
    cmp -s "$1" "$2" || record_fail "$3"
}

assert_exists() {
    [ -e "$1" ] || record_fail "expected $1 to exist"
}

assert_absent() {
    if [ -e "$1" ]; then
        record_fail "expected $1 to be absent"
    fi
}

assert_mode() {
    mode=$(stat -c %a "$1" 2>/dev/null || echo '?')
    if [ "$mode" != "$2" ]; then
        record_fail "expected $1 to have mode $2, got $mode"
    fi
}

assert_no_leftovers() {
    dir=$1
    if [ -d "$dir" ] && [ -n "$(find "$dir" -name '.patok.new.*' -print -quit)" ]; then
        record_fail "leftover .patok.new.* file in $dir"
    fi
}

assert_url_requested() {
    log=$1/fixtures/urls.log
    if [ ! -f "$log" ] || ! grep -qF -- "$2" "$log"; then
        record_fail "expected a request for: $2"
    fi
}

assert_no_urls() {
    log=$1/fixtures/urls.log
    if [ -s "$log" ]; then
        record_fail "expected no network requests, but urls.log is not empty"
    fi
}

case_1() {
    begin_case 'sh -n syntax check'
    sh -n "$INSTALL_SH" || record_fail 'install.sh failed sh -n'
    sh -n "$0" || record_fail 'harness failed sh -n'
    end_case
}

case_2() {
    begin_case 'Linux/x86_64 happy path'
    run_install
    assert_status 0
    assert_contains 'Installed patok v1.2.3 to'
    assert_exists "$case_work/install/patok"
    assert_mode "$case_work/install/patok" 755
    assert_file_equals "$case_work/install/patok" "$case_work/fixtures/patok" \
        'installed binary does not match the fixture archive'
    assert_url_requested "$case_work" '/releases/latest'
    assert_url_requested "$case_work" 'patok-x86_64-unknown-linux-musl.tar.gz'
    assert_no_leftovers "$case_work/install"
    end_case
}

case_3() {
    begin_case 'Darwin/arm64 and Darwin/aarch64 happy path'
    uname_s=Darwin
    uname_m=arm64
    run_install
    assert_status 0
    assert_contains 'Installed patok v1.2.3 to'
    assert_url_requested "$case_work" 'patok-aarch64-apple-darwin.tar.gz'
    assert_file_equals "$case_work/install/patok" "$case_work/fixtures/patok" \
        'installed binary does not match the fixture archive'
    uname_m=aarch64
    run_install
    assert_status 0
    assert_url_requested "$case_work" 'patok-aarch64-apple-darwin.tar.gz'
    end_case
}

case_4() {
    begin_case 'Darwin/x86_64 happy path'
    uname_s=Darwin
    uname_m=x86_64
    run_install
    assert_status 0
    assert_contains 'Installed patok v1.2.3 to'
    assert_url_requested "$case_work" 'patok-x86_64-apple-darwin.tar.gz'
    assert_file_equals "$case_work/install/patok" "$case_work/fixtures/patok" \
        'installed binary does not match the fixture archive'
    end_case
}

case_5() {
    begin_case 'checksum mismatch aborts with no files written'
    fx=$case_work/fixtures
    awk '{
        if ($2 == "patok-x86_64-unknown-linux-musl.tar.gz")
            print "0000000000000000000000000000000000000000000000000000000000000000  " $2
        else
            print
    }' "$fx/checksums" >"$fx/checksums.new"
    mv "$fx/checksums.new" "$fx/checksums"
    run_install
    assert_status 1
    assert_contains 'checksum mismatch'
    assert_absent "$case_work/install/patok"
    assert_no_leftovers "$case_work/install"
    end_case
}

case_6() {
    begin_case 'checksum matching is exact-filename only'
    fx=$case_work/fixtures
    hash=$(sha256sum "$fx/patok-x86_64-unknown-linux-musl.tar.gz" | cut -d ' ' -f 1)
    {
        printf '%s  patok-x86_64-unknown-linux-musl.tar\n' "$hash"
        printf '%s  patok-other.tar.gz\n' "$hash"
    } >"$fx/checksums"
    run_install
    assert_status 1
    assert_contains 'no checksum listed'
    assert_absent "$case_work/install/patok"
    assert_no_leftovers "$case_work/install"
    end_case
}

case_7() {
    begin_case 'archive download failure'
    echo 'https://github.com/test/test/releases/download/v1.2.3/patok-x86_64-unknown-linux-musl.tar.gz' \
        >"$case_work/fixtures/curl-fail"
    run_install
    assert_status 1
    assert_contains 'failed to download'
    assert_absent "$case_work/install/patok"
    assert_no_leftovers "$case_work/install"
    end_case
}

case_8() {
    begin_case 'GitHub API failure'
    echo 'https://api.github.com/repos/test/test/releases/latest' \
        >"$case_work/fixtures/curl-fail"
    run_install
    assert_status 1
    assert_contains 'could not query'
    assert_absent "$case_work/install/patok"
    end_case
}

case_9() {
    begin_case 'checksums download failure'
    echo 'https://github.com/test/test/releases/download/v1.2.3/checksums' \
        >"$case_work/fixtures/curl-fail"
    run_install
    assert_status 1
    assert_contains 'failed to download checksums'
    assert_absent "$case_work/install/patok"
    end_case
}

case_10() {
    begin_case 'archive without patok at its root is rejected'
    fx=$case_work/fixtures
    archive=patok-x86_64-unknown-linux-musl.tar.gz
    mkdir "$fx/patok-1.2.3"
    cp "$fx/patok" "$fx/patok-1.2.3/patok"
    tar -czf "$fx/$archive" -C "$fx" patok-1.2.3
    rm -rf "$fx/patok-1.2.3"
    hash=$(sha256sum "$fx/$archive" | cut -d ' ' -f 1)
    printf '%s  %s\n' "$hash" "$archive" >"$fx/checksums"
    run_install
    assert_status 1
    assert_contains 'archive does not contain a patok binary'
    assert_absent "$case_work/install/patok"
    assert_no_leftovers "$case_work/install"
    end_case
}

case_11() {
    begin_case '--clean removes the prior install and data directory'
    printf 'old\n' >"$case_work/install/patok"
    mkdir -p "$case_work/data/patok"
    printf 'old\n' >"$case_work/data/patok/keep"
    run_install --clean
    assert_status 0
    assert_contains 'Cleaning: removing'
    assert_absent "$case_work/data/patok"
    assert_file_equals "$case_work/install/patok" "$case_work/fixtures/patok" \
        'installed binary does not match the fixture archive'
    assert_contains 'Installed patok v1.2.3 to'
    end_case
}

case_12() {
    begin_case '--clean falls back to HOME/.local/share/patok when XDG_DATA_HOME is unset'
    mkdir -p "$case_work/home/.local/share/patok"
    printf 'old\n' >"$case_work/home/.local/share/patok/keep"
    unset_xdg=1
    run_install --clean
    assert_status 0
    assert_contains "Cleaning: removing $case_work/install/patok and $case_work/home/.local/share/patok"
    assert_absent "$case_work/home/.local/share/patok"
    assert_contains 'Installed patok v1.2.3 to'
    end_case
}

case_13() {
    begin_case 'unknown option is rejected before any download'
    run_install --bogus
    assert_status 1
    assert_contains 'unknown option'
    assert_absent "$case_work/install/patok"
    assert_no_urls "$case_work"
    end_case
}

case_14() {
    begin_case '-h and --help print usage without downloading or installing'
    run_install -h
    assert_status 0
    assert_contains 'usage: install.sh [--clean]'
    assert_absent "$case_work/install/patok"
    assert_no_urls "$case_work"
    run_install --help
    assert_status 0
    assert_contains 'usage: install.sh [--clean]'
    assert_absent "$case_work/install/patok"
    assert_no_urls "$case_work"
    end_case
}

case_15() {
    begin_case 'Linux arm64 is rejected'
    uname_s=Linux
    uname_m=aarch64
    run_install
    assert_status 1
    assert_contains 'is not supported'
    assert_absent "$case_work/install/patok"
    assert_no_urls "$case_work"
    uname_m=arm64
    run_install
    assert_status 1
    assert_contains 'is not supported'
    assert_no_urls "$case_work"
    end_case
}

case_16() {
    begin_case 'unsupported platform is rejected'
    uname_s=FreeBSD
    uname_m=amd64
    run_install
    assert_status 1
    assert_contains 'unsupported platform'
    assert_absent "$case_work/install/patok"
    assert_no_urls "$case_work"
    end_case
}

main() {
    if [ ! -f "$INSTALL_SH" ]; then
        printf 'install.sh not found at %s\n' "$INSTALL_SH" >&2
        exit 1
    fi
    case_1
    case_2
    case_3
    case_4
    case_5
    case_6
    case_7
    case_8
    case_9
    case_10
    case_11
    case_12
    case_13
    case_14
    case_15
    case_16
    printf '%d passed, %d failed\n' "$pass" "$fail"
    if [ "$fail" -ne 0 ]; then
        exit 1
    fi
}

main
